n, m = map(int, input().split())
N = set(int(input()) for i in range(n))
M = set(int(input()) for i in range(m))
print(len(N & M))
print(*sorted(N & M))
print(len(N - M))
print(*sorted(N - M))
print(len(M - N))
print(*sorted(M - N))